namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - ryltsevavikyla-coder
description: Collection with a custom module that creates a text file
license:
  - GPL-3.0-or-later
tags:
  - module
  - file
repository: https://github.com/ryltsevavikyla-coder/my_own_collection
